### ISSUE TITLE
orientation changes stretch the video

### ISSUE THREAD

**Issue by c1ngular** [NathanaelA/nativescript-exoplayer#1]
wonderful plugin , thanks ! tried your demo ,working great ! though after change of orientation , aspect ratio of video won't keep on Android platform [tried to set fill property to false] ! same issue with brad martin's plugin ! or this is the default behavior ? 

P.S. noticed the vp.java file from your demo folder , is it in use , if it was , how? thanks !

**Comment by NathanaelA** [comment]
Probably the default behavior; but it should be fixable.

vp.java; left over source ; shouldn't be there...  Oops..  ;-)

**Comment by NathanaelA** [comment]
This has been pushed in 3.2 thanks to @SemenovAlexander
