### ISSUE TITLE
Not compatable with nativescript 3.4

### ISSUE THREAD

**Issue by mordeccai** [NathanaelA/nativescript-exoplayer#22]
When I run tns build android --bundle i get the following error:

> Refreshing application...
> Successfully synced application org.nativescript.moviezurb on device HT543YB00350.
> ActivityManager: Start proc org.nativescript.moviezurb for activity org.nativescript.moviezurb/com.tns.NativeScriptActivity: pid=10695 uid=10279 gids={50279, 1028, 1015, 3003, 5012}
> System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.moviezurb/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
> System.err: Calling js method onCreate failed
> System.err: Error: Building UI from XML. @file:///app/pages/home/home-page.xml:9:13
> System.err:  > Module '/data/data/org.nativescript.moviezurb/files/app/nativescript-exoplayer' not found for element 'nativescript-exoplayer:Video'.
> System.err:    > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.moviezurb/files/app/nativescript-exoplayer", relative to: app//
> System.err:       com.tns.Module.resolvePathHelper(Module.java:146)
> System.err:     com.tns.Module.resolvePath(Module.java:55)
> System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
> System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
> System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
> System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
> System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
> System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
> System.err:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
> System.err:     android.app.Activity.performCreate(Activity.java:5312)
> System.err:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
> System.err:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
> System.err:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
> System.err:     android.app.ActivityThread.access$800(ActivityThread.java:153)
> System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
> System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
> System.err:     android.os.Looper.loop(Looper.java:157)
> System.err:     android.app.ActivityThread.main(ActivityThread.java:5633)
> System.err:     java.lang.reflect.Method.invokeNative(Native Method)
> System.err:     java.lang.reflect.Method.invoke(Method.java:515)
> System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
> System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
> System.err:     dalvik.system.NativeStart.main(Native Method)
> System.err: File: "file:///data/data/org.nativescript.moviezurb/files/app/vendor.js, line: 11129, column: 20
> System.err: StackTrace:
> System.err:     Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 8142, column: 24
> System.err:     Frame: function:'SourceError', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 8153, column: 23
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 11148, column: 17
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 11129, column: 33
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 27584, column: 13
> System.err:     Frame: function:'module.exports.EasySAXParser.parse', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 28452, column: 23
> System.err:     Frame: function:'module.exports.XmlParser.parse', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 27631, column: 22
> System.err:     Frame: function:'module.exports.XmlStringParser.parse', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 11135, column: 27
> System.err:     Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 10968, column: 11
> System.err:     Frame: function:'loadPage', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 11064, column: 27
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 13024, column: 26
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 13043, column: 20
> System.err:     Frame: function:'module.exports.FrameBase.navigate', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 13143, column: 28
> System.err:     Frame: function:'module.exports.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 5953, column: 19
> System.err:     Frame: function:'module.exports.NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 33121, column: 25
> System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
> System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
> System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:153)
> System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
> System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
> System.err:     at android.os.Looper.loop(Looper.java:157)
> System.err:     at android.app.ActivityThread.main(ActivityThread.java:5633)
> System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
> System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
> System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
> System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
> System.err:     at dalvik.system.NativeStart.main(Native Method)
> System.err: Caused by: com.tns.NativeScriptException:
> System.err: Calling js method onCreate failed
> System.err: Error: Building UI from XML. @file:///app/pages/home/home-page.xml:9:13
> System.err:  > Module '/data/data/org.nativescript.moviezurb/files/app/nativescript-exoplayer' not found for element 'nativescript-exoplayer:Video'.
> System.err:    > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.moviezurb/files/app/nativescript-exoplayer", relative to: app//
> System.err:       com.tns.Module.resolvePathHelper(Module.java:146)
> System.err:     com.tns.Module.resolvePath(Module.java:55)
> System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
> System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
> System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
> System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
> System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
> System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
> System.err:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
> System.err:     android.app.Activity.performCreate(Activity.java:5312)
> System.err:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
> System.err:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
> System.err:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
> System.err:     android.app.ActivityThread.access$800(ActivityThread.java:153)
> System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
> System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
> System.err:     android.os.Looper.loop(Looper.java:157)
> System.err:     android.app.ActivityThread.main(ActivityThread.java:5633)
> System.err:     java.lang.reflect.Method.invokeNative(Native Method)
> System.err:     java.lang.reflect.Method.invoke(Method.java:515)
> System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
> System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
> System.err:     dalvik.system.NativeStart.main(Native Method)
> System.err: File: "file:///data/data/org.nativescript.moviezurb/files/app/vendor.js, line: 11129, column: 20
> System.err: StackTrace:
> System.err:     Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 8142, column: 24
> System.err:     Frame: function:'SourceError', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 8153, column: 23
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 11148, column: 17
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 11129, column: 33
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 27584, column: 13
> System.err:     Frame: function:'module.exports.EasySAXParser.parse', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 28452, column: 23
> System.err:     Frame: function:'module.exports.XmlParser.parse', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 27631, column: 22
> System.err:     Frame: function:'module.exports.XmlStringParser.parse', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 11135, column: 27
> System.err:     Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 10968, column: 11
> System.err:     Frame: function:'loadPage', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 11064, column: 27
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 13024, column: 26
> System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 13043, column: 20
> System.err:     Frame: function:'module.exports.FrameBase.navigate', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 13143, column: 28
> System.err:     Frame: function:'module.exports.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 5953, column: 19
> System.err:     Frame: function:'module.exports.NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.moviezurb/files/app/vendor.js', line: 33121, column: 25
> System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
> System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
> System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
> System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
> System.err:     at android.app.Activity.performCreate(Activity.java:5312)
> System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
> System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
> System.err:     ... 11 more
> ActivityManager: R

ecipient 10695

**Comment by suralal** [comment]
i have a video coming from server , but not able to play.
but the demo videos is working fine

platform : android it is working fine
                 ios is the problem

example video url coming from server : https://millasays-apollo-dev.azurewebsites.net/api/v1/files/ElhZGLePQYTx5DDKKsyGsqXM0TCJlGlfmnE70OQjZfes5PI5SOylmOKXOVjxIVoK.mp4

**Comment by NathanaelA** [comment]
@suralal - You should create a new issue; and if you can drop a link to a demo repo that exhibits the issue.

**Comment by NathanaelA** [comment]
@mordeccai - Sorry, I'm not sure about webpack issues; that is typically a webpack problem.
