### ISSUE TITLE
get the instance of exoplayer in nativescript

### ISSUE THREAD

**Issue by Mubashir-Mohamed** [NathanaelA/nativescript-exoplayer#26]
I import {registerElement} from "nativescript-angular/element-registry";
registerElement("VideoPlayer", () => require("nativescript-videoplayer").Video);

In angular how can i get the instance of video player in angualr fro executing various operations like play 
play() - Start playing the video
pause() - Pause the video

**Comment by umair-ameen** [comment]
@Mubashir-Mohamed  Use viewchild

**Comment by peprog** [comment]
I used view child but I have still problem, here is my code:
in component:

@ViewChild('player')
private player:  ElementRef;


and in my view:
<exoplayer *ngIf="is_loaded" id="player"
               [src]="episode.link
               playbackReady="change_player_quality"
               autoplay="true"
               height="300"
               class="exoplayer" #player></exoplayer>

but when I console the this.player after player init I get this: 
{
"nativeElement": {"_observers": {"_ngcontent-c2Change": [{}]},
"_onLoadedCalled": true,
"_onUnloadedCalled": false,
"_cssState": {
"view": "[Circular]",
"_matchInvalid": false,
"_match": {"changeMap": {},
"selectors": [{"selectors": [{"cssClass": "exoplayer"},{"attribute": "_ngcontentc2"}],
"specificity": 512,
"head": "[Circular]",
"dynamic": true,
"ruleset": {"selectors": ["[Circular]"],
"declarations": [{"property": "margin-top","value": "0px"}]}}]},
"_appliedChangeMap": "[Circular]",

and this.player dose not have .src property.

can you help me please with that?
