### ISSUE TITLE
How to modify player controller layout and add buttons in angular

### ISSUE THREAD

**Issue by icipiqkm** [NathanaelA/nativescript-exoplayer#28]
I am a newbie. Please forgive me for the idiot problem. I want to add a full-screen button to the default controller, and I want to modify the default similarity (play button, delete forward button, adjust the size and position of the play button) Style, I am using angular. I don't understand exactly how to do it. I don't see any related options in the plugin. Hope someone can help me.

**Comment by NathanaelA** [comment]
Use a GridLayout; you can embed whatever buttons you want in a GridLayout and also embed the player in the GridLayout.
