### ISSUE TITLE
breaks in Nativescript 3.0

### ISSUE THREAD

**Issue by developper89** [NathanaelA/nativescript-exoplayer#3]
Hello, 
This plugin is no longer functional in nativescript 3.0.
Are you planning to release a compatible version of this plugin ?

**Comment by NathanaelA** [comment]
This is to be expected,  2.5 to 3.0 had breaking changes which breaks any plugins that are visual, have properties or css properties...    At some point we will convert it.

**Comment by bnussey** [comment]
Hi @developper89 we have now updated to version 3.0 .. please review and test, thank you.
