### ISSUE TITLE
works on some m3u8 files

### ISSUE THREAD

**Issue by advisweb** [NathanaelA/nativescript-exoplayer#32]
Hi,

This is a great plugin, thank you for the great work!
However, I seem to face an unusual behaviour, where some m3u8 files are loaded nicely and the others are not loaded. Leaving me with a white screen without error.
Haven't tested in iOS, but this behaviour is happening in Android.

Is there more detailed error log, I can spit out to see what's causing the white screen?
Thank you,

**Comment by NathanaelA** [comment]
Not sure of any better error log beyond the `adb logcat` as it normally outputs what is going on.   If you have a .m3u8 file that doesn't work; then it should be just try it while watching the adb logcat and I believe that should tell you why it failed.

**Comment by advisweb** [comment]
Thank you for your help, I'll give it a shot.

**Comment by NathanaelA** [comment]
If you can provide a test case that fails; I will re-open this.
