### ISSUE TITLE
ios playbackReady won't fire

### ISSUE THREAD

**Issue by peppeg85** [NathanaelA/nativescript-exoplayer#34]
hello, thanks for the plugin. on ios i've this issue: the playbackReady event won't fire, anyone else has this behaviour?how can i fix it?

thank you again

**Comment by NathanaelA** [comment]
Did you try the demo app; did it work or not?

**Comment by noordw** [comment]
@peppeg85 Did you find what was causing this?.

**Comment by peppeg85** [comment]
sorry but....i don't remember if and how i fixed, i have this code:

  ```
  <exoplayer:Video id="videoID"
                                     controls="false"
                                     loop="false" autoplay="false"
                                     playbackReady="videoReady"
                                     tap="controls" fill="{{ videoFill }}"
                    />
```

and in js:
```
 function videoReady() {
// your stuff
}

exports.videoReady = videoReady;
```
i hope it works
