### ISSUE TITLE
Duplicate identifier in v4

### ISSUE THREAD

**Issue by joshcomley** [NathanaelA/nativescript-exoplayer#40]
Hi,

I'm getting the following error at compile time:

    ERROR in node_modules/nativescript-exoplayer/videoplayer.d.ts(25,3): error TS2300: Duplicate identifier 'observeCurrentTime'.
    node_modules/nativescript-exoplayer/videoplayer.d.ts(84,3): error TS2300: Duplicate identifier 'observeCurrentTime'.

I can see in the `videoplayer.d.ts` file that the `Video` class declares both a property called `observeCurrentTime` and a method.

This bug is currently preventing compilation.

Many thanks!
Josh

**Comment by ofe2358** [comment]
As a workaround, i tried commenting line 25 of file   \node_modules\nativescript-exoplayer/videoplayer.d.ts   succesfully at least for compilation

**Comment by Ianc22** [comment]
Found same issue, been doing my head in for months! Only just discovered it's the damned plugin. My compiler wasn't shouting about the error, and the app will just hang with the debugger timing out. Anyhow, commenting out line 84 sorted this out for me, I has a look at the implementations and couldn't find a ref to the function, however there is a check on the boolean. Doesn't look like that method is used anywhere, can you guys pls sort it? thx! ;)
