### ISSUE TITLE
Subtitle Support 

### ISSUE THREAD

**Issue by jibon57** [NathanaelA/nativescript-exoplayer#5]
Hello,

Thanks for the plugin. Is it possible to add subtitle (.srt) with the video? 

Thanks

**Comment by NathanaelA** [comment]
I'm sure it is possible.

I'm willing to accept a pull requests for the plugin to add this feature if you (or someone else) wants to do it.   You can also hire me or another contractor to implement this feature if you are so inclined.

**Comment by jibon57** [comment]
@NathanaelA, I have sent you an email.

**Comment by jibon57** [comment]
@NathanaelA , Please review & merge the pull request :)

**Comment by NathanaelA** [comment]
This has been released in  in v3.2.0  Thanks to @SemenovAlexander
