### ISSUE TITLE
Use nativescript-exoplayer with nativescript-vue (vue.js)

### ISSUE THREAD

**Issue by jechazelle** [NathanaelA/nativescript-exoplayer#52]
I would like to know how can I use exoplayer with nativescript vuejs please ?

I tried this :

    import exoplayer from 'nativescript-exoplayer'
    ...
    components: {
        exoplayer
    },

and in my template :

    <exoplayer id="nativeexoplayer"
        controls="true"
        loop="true" autoplay="false" height="280"
        src="~/assets/videos/video1.mp4" />

But I have this error :

> Unknown custom element: <exoplayer> - did you register the component
> correctly? For recursive components, make sure to provide the "name"
> option.

**Comment by NathanaelA** [comment]
You need to use `registerElement` like so:

Vue.registerElement('exoplayer', () => exoplayer);

**Comment by jechazelle** [comment]
@NathanaelA I tried to use the registerElement :

```
// main.js 
import exoplayer from 'nativescript-exoplayer'
Vue.registerElement('exoplayer', () => exoplayer);
```

```
// component
<exoplayer id="nativeexoplayer"
                       controls="true"
                       loop="true" autoplay="false" height="280"
                       src="~/assets/videos/video1.mp4" />
```

But I have this error : 

> Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'node.setAttribute')
