### ISSUE TITLE
Can I use this to play youtube videos without nativescript-youtube-parser ?

### ISSUE THREAD

**Issue by ishandutta2007** [NathanaelA/nativescript-exoplayer#6]
For https://github.com/bradmartin/nativescript-videoplayer
you can't play directly unless you parse using http://plugins.nativescript.org/plugin/nativescript-youtube-parser

**Comment by NathanaelA** [comment]
I don't believe so; the youtube parser parses the configuration that youtube sends.   You need to do the work to parse the data file and choose which size video you want to play and then play it.

**Comment by ishandutta2007** [comment]
Even after using parsed youtube url(parsed offline ie outside the app), it's terribly slow compared to to the big_buck_bunny.mp4 in the example.
What should be done, what do you suggest ?
