### ISSUE TITLE
Loading many external files in ListView

### ISSUE THREAD

**Issue by madjor5** [NathanaelA/nativescript-exoplayer#60]
I have a news-app where I load a lot of videos through an Amazon account into nativescript-exoplayer.

The result is, that it doesn't load and it seems it doesn't even try. My best bet is, that it is dealing with too many items.

The construction is similar to this:

```<ListView [items]="elements" marginRight="-2" separatorColor="transparent">
    <ng-template let-item="item">
      <StackLayout rows="*" [ngSwitch]="item.type">
        <GridLayout *ngSwitchCase="'video'">
          <Label [text]="item.relation.mediaInfo.videos[0].uri" textWrap="true"></Label>
          <exoplayer
          id="{{item.id}}"
          src="{{item.relation.mediaInfo.videos[0].uri}}"
          autoplay="false"
          height="200"
          (playbackReady)="videoPlaybackReady()"></exoplayer>
        </GridLayout>
        <GridLayout *ngSwitchDefault backgroundColor="gray">
          <Label [text]="item.type"></Label>
        </GridLayout>
      </StackLayout>
    </ng-template>
  </ListView>
```

And visually the result is like
![Simulator Screen Shot - iPhone 11 - 2020-07-25 at 10 23 55](https://user-images.githubusercontent.com/1782249/88452678-fc1a8480-ce60-11ea-874a-158b4be0e7b1.png)

All the video paths are correct and are videos from AWS.

Any ideas?

**Comment by NathanaelA** [comment]
Do any of the videos load or all of them look like this?

**Comment by madjor5** [comment]
All of them look like this. I have a feeling that it is whenever a file is in S3. It loads fine - even on iOS Safari, just not within the plugin.

Perhaps it could be headers?

**Comment by madjor5** [comment]
I have logged this issue: https://github.com/nstudio/nativescript-videoplayer/issues/171 in `nativescript-videoplayer` that might be more correct than the fact that it might load in or out of a list-view. So I am OK with closing this issue now.
