### ISSUE TITLE
Error loading component on iOS 14 in Nativescript 7

### ISSUE THREAD

**Issue by mreall** [NathanaelA/nativescript-exoplayer#63]
When trying to display the exoplayer on iOS using Nativescript 7, I get the following error:
`TypeError: Class constructor View cannot be invoked without 'new'`

This worked before upgrading to NS7, so I assume it's not yet compatible.  Is there an easy solution?

My `ns info`:
Component nativescript has 7.0.8 version and is up to date.
Component @nativescript/core has 7.0.3 version and is up to date.
Component @nativescript/ios has 7.0.0 version and is up to date.
Component @nativescript/android has 7.0.0 version and is up to date.

**Comment by NathanaelA** [comment]
This has been moved & fixed in the @nstudio/nativescript-exoplayer version.
