### ISSUE TITLE
Module 'nativescript-exoplayer' not found for element 'nativescript-exoplayer:Video'

### ISSUE THREAD

**Issue by kryptus36** [NathanaelA/nativescript-exoplayer#67]
This may be related to #22.

✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.1.2 version and is up to date.
✔ Component @nativescript/core has 7.1.3 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.1 version and is up to date.

"dependencies": {
    "@nativescript-community/ui-pager": "^13.0.0-alpha.10",
    "@nativescript/appversion": "^2.0.0",
    "@nativescript/core": "~7.1.0",
    "@nativescript/firebase": "^11.0.0",
    "@nativescript/geolocation": "^7.0.0",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/secure-storage": "^3.0.0",
    "@nativescript/theme": "^3.0.0",
    "@proplugins/nativescript-orientation": "^2.5.0",
    "@types/node": "^12.12.7",
    "moment": "^2.27.0",
    "moment-timezone": "^0.5.28",
    "nativescript-audio-player": "^1.0.3",
    "nativescript-exoplayer": "^4.0.2",
    "nativescript-insomnia": "^2.0.0",
    "nativescript-mqtt": "^3.0.0",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-webview-interface": "^1.4.4"
  },

JS: Error: Building UI from XML. @./views/pages/videotest/videotest-page.xml:7:7
JS:  > Module 'nativescript-exoplayer' not found for element 'nativescript-exoplayer:Video'.
JS:    > Class constructor View cannot be invoked without 'new'
JS: error repo - reporting
JS: discarded Error: Calling js method onTouch failed
JS: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
JS: error repo - reporting
System.err: An uncaught Exception occurred on "main" thread.
System.err: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
System.err: 
System.err: StackTrace:
System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
System.err:     at com.tns.gen.java.lang.Object_vendor_21279_28_TouchListenerImpl.onTouch(Object_vendor_21279_28_TouchListenerImpl.java:19)
System.err:     at android.view.View.dispatchTouchEvent(View.java:12509)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
System.err:     at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
System.err:     at android.view.View.dispatchPointerEvent(View.java:12752)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
System.err:     at android.os.MessageQueue.next(MessageQueue.java:326)
System.err:     at android.os.Looper.loop(Looper.java:160)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
JS: uncaughterror Error: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
System.err: com.tns.NativeScriptException: Error: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
System.err:     at com.tns.Runtime.passExceptionToJsNative(Native Method)
System.err:     at com.tns.Runtime.passUncaughtExceptionToJs(Runtime.java:84)
System.err:     at com.tns.NativeScriptUncaughtExceptionHandler.uncaughtException(NativeScriptUncaughtExceptionHandler.java:34)
System.err:     at com.google.android.gms.ads.internal.report.b.uncaughtException(:com.google.android.gms.policy_ads_fdr_dynamite@204204100@204204100057.336078696.336078696:3)
System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
System.err:     at com.google.android.gms.ads.internal.report.c.uncaughtException(:com.google.android.gms.policy_ads_fdr_dynamite@204204100@204204100057.336078696.336078696:3)
System.err:     at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
^C

**Comment by NathanaelA** [comment]
Please note this plugin moved to https://github.com/nstudio/nativescript-plugins/ so support is there/
