### ISSUE TITLE
Demo project is broken 

### ISSUE THREAD

**Issue by SemenovAlexander** [NathanaelA/nativescript-exoplayer#7]
Hello,
I'm trying to run demo project from repository, but it seems to be broken, following error raises:
`app/main-view-model.ts(5,23): error TS2307: Cannot find module 'nativescript-exoplayer'.`

**Comment by NathanaelA** [comment]
Did you try; `tns plugin add nativescript-exoplayer` from inside the demo folder.

**Comment by SemenovAlexander** [comment]
Yeap, it says plugin already added. I've tried to remove plugin and add it back - same result.

**Comment by NathanaelA** [comment]
Hmm, thanks for the bug report.  I'll test a fresh cloned copy and see what I messed up.  :grinning:

**Comment by NathanaelA** [comment]
I have uploaded a new version, see if the demo is now fixed for you.

**Comment by SemenovAlexander** [comment]
Thanks, it works fine now if I add plugin from repository ( using `tns plugin add nativescript-exoplayer` ).

However, I want to make some changes to plugin and try to add plugin from local sources ( `tns plugin add ..`) - it shows error:

`Path must be a string. Received undefined`

And, when I try to build demo with such setup - another error raises:
`Processing node_modules failed. Error: cp: cannot create directory
'/Volumes/Workspace/js/nativescript-exoplayer/demo/platforms/ios/demo/app/tns_modules': No 
 such file or directory`

**Comment by NathanaelA** [comment]
I cannot duplicate this.  What I did is:

```
tsc
cd demo
tns plugin remove nativescript-exoplayer
tns plugin add ..
```

You have to transpile the TS code into JS; so that is the `tsc` then you remove the current plugin and add the plugin from the root directory.   At that point you should be running the latest code.

**Comment by NathanaelA** [comment]
Please note just as an update with the new version the path will be to 
`tns plugin add ../src`  not `tns plugin add ..`
